### ISSUE TITLE
Troubles with python autocomplete.

### ISSUE THREAD

**Issue by maximglyzin** [bigeyex/brackets-wordhint#5]
Hellow. I've installed the 'WordHint' extension and it not work for python. I could not find any documentation or simular issue about it. I use Mint 17 64-bit/ brackets 1.0. I don't have any idea whats wrong.

**Comment by caiohamamura** [comment]
Yeah, it won't work. Anybody maintaining this extension?

[EDIT]
By viewing the code, the only thing that it really does is to provide autocomplete for already written words.I think the best we can do is to provide a list of keywords to autocomplete beforehand, but it will never work for imports since it is pure javascript/html without cgi capabilities.

**Comment by Garito** [comment]
My console raises this:

 Exception in 'editorChange' listener on Editor TypeError: undefined is not a function TypeError: undefined is not a function
    at WordHints.getHints (file:///Users/garito/Library/Application%20Support/Brackets/extensions/user/bigeyex.brackets-wordhint/main.js:143:39)
    at _updateHintList (/editor/CodeHintManager.js:426:40)
    at _beginSession (/editor/CodeHintManager.js:515:13)
    at _handleChange (/editor/CodeHintManager.js:629:17)
    at Editor.trigger (/utils/EventDispatcher.js:222:40)
    at Editor._handleEditorChange (/editor/Editor.js:870:14)
    at eval (/editor/Editor.js:412:18)
    at Editor.trigger (/utils/EventDispatcher.js:222:40)
    at eval (/editor/Editor.js:941:18)
    at CodeMirror.signal (/thirdparty/CodeMirror/lib/codemirror.js:8042:49)extensions/default/DebugCommands/ErrorNotification.js:125 window.console.error
/utils/EventDispatcher.js:225 Assertion failed:/utils/EventDispatcher.js:225 trigger
